import type {
  BlogPost,
  CartItem,
  Order,
  Product,
  ProductCategory,
  Service,
  Testimonial,
} from "@/types";

export const SITE = {
  name: "Printoe",
  tagline: "Enterprise print, perfected.",
  description:
    "Premium online printing for brands that demand precision, speed, and craftsmanship.",
  url: "https://printoe.com",
  email: "hello@printoe.com",
  phone: "+1 (888) 555-0199",
  address: "450 Market Street, Suite 1200, San Francisco, CA 94105",
};

/** Popular Products order aligned with UPrinting homepage sidebar */
export const categories: ProductCategory[] = [
  {
    id: "1",
    name: "Apparel",
    slug: "apparel",
    description: "Custom branded apparel and wearables",
    count: 4,
    startingPrice: 14.99,
    icon: "Shirt",
    color: "#FFD400",
  },
  {
    id: "2",
    name: "Banners",
    slug: "banners",
    description: "Indoor & outdoor vinyl and display banners",
    count: 6,
    startingPrice: 15.8,
    icon: "Flag",
    color: "#1A1A1A",
  },
  {
    id: "3",
    name: "Boxes",
    slug: "boxes",
    description: "Mailer, product, and shipping boxes",
    count: 5,
    startingPrice: 299.99,
    icon: "Box",
    color: "#00AEEF",
  },
  {
    id: "4",
    name: "Brochures",
    slug: "brochures",
    description: "Folded marketing brochures and booklets",
    count: 3,
    startingPrice: 189.99,
    icon: "BookOpen",
    color: "#1A1A1A",
  },
  {
    id: "5",
    name: "Business Cards",
    slug: "business-cards",
    description: "Standard and premium business cards",
    count: 14,
    startingPrice: 32.12,
    icon: "CreditCard",
    color: "#E6007A",
  },
  {
    id: "6",
    name: "Flyers",
    slug: "flyers",
    description: "Business and promotional flyer printing",
    count: 4,
    startingPrice: 89.99,
    icon: "FileText",
    color: "#00AEEF",
  },
  {
    id: "7",
    name: "Labels",
    slug: "labels",
    description: "Product, bottle, and roll labels",
    count: 4,
    startingPrice: 34.99,
    icon: "Tag",
    color: "#E30613",
  },
  {
    id: "8",
    name: "Packaging",
    slug: "packaging",
    description: "Bags, pouches, tape, and packaging",
    count: 8,
    startingPrice: 39.4,
    icon: "Package",
    color: "#E6007A",
  },
  {
    id: "9",
    name: "Postcards",
    slug: "postcards",
    description: "Standard and oversized postcards",
    count: 4,
    startingPrice: 90.47,
    icon: "Image",
    color: "#00A651",
  },
  {
    id: "10",
    name: "Promotional Products",
    slug: "promotional-products",
    description: "Tents, drinkware, and giveaways",
    count: 7,
    startingPrice: 0.62,
    icon: "Gift",
    color: "#E30613",
  },
  {
    id: "11",
    name: "Signs",
    slug: "signs",
    description: "Yard signs, wall decals, and signage",
    count: 7,
    startingPrice: 14.13,
    icon: "Megaphone",
    color: "#00A651",
  },
  {
    id: "12",
    name: "Stickers",
    slug: "stickers",
    description: "Die-cut, vinyl, roll, and sheet stickers",
    count: 10,
    startingPrice: 29.99,
    icon: "Sticker",
    color: "#FFD400",
  },
  {
    id: "13",
    name: "Marketing Materials",
    slug: "marketing-materials",
    description: "Menus, forms, notepads, and more",
    count: 8,
    startingPrice: 42.68,
    icon: "FileText",
    color: "#00AEEF",
  },
  {
    id: "14",
    name: "Posters",
    slug: "posters",
    description: "Bulk and large-format posters",
    count: 4,
    startingPrice: 19.99,
    icon: "Image",
    color: "#1A1A1A",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Silk Business Cards",
    slug: "silk-business-cards",
    category: "business-cards",
    description:
      "Soft-touch laminated cards with razor-sharp color and a luxurious matte feel—ideal for premium brand first impressions.",
    price: 29.99,
    compareAt: 39.99,
    rating: 4.9,
    reviews: 1284,
    deliveryDays: 3,
    badge: "Best Seller",
    image: "business-cards",
    images: ["business-cards", "business-cards-2", "business-cards-3"],
    imageUrl:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542744094-24638efffd90?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["16pt Soft Touch", "14pt Matte", "18pt Spot UV", "100 lb. Gloss Cover"],
    sizes: ['3.5" × 2"', '3.5" × 2" Rounded', 'Square 2.5"', "Slim"],
    finishes: ["Matte", "Soft Touch", "Spot UV", "Foil"],
    printedSides: ["Front Only", "Front & Back"],
    bundling: ["None", "25 per pack", "50 per pack", "100 per pack"],
    turnaround: ["3 Business Days", "2 Business Days", "Next Business Day"],
    highlights: [
      '3.5" × 2" and more sizes including custom',
      "Soft-touch, matte, gloss, and foil finishes",
      "Single- or double-sided printing",
      "Free artwork check before print",
    ],
    featured: true,
  },
  {
    id: "p2",
    name: "Business Flyers",
    slug: "business-flyers",
    category: "flyers",
    description:
      "High-impact business flyers on premium stock—perfect for promotions, menus, and event marketing with optional folding.",
    price: 0.29,
    rating: 4.5,
    reviews: 1002,
    deliveryDays: 3,
    badge: "Popular",
    image: "brochures",
    images: ["brochures", "brochures-2", "posters"],
    imageUrl:
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["100 lb. Paper Gloss", "100 lb. Paper Matte", "80 lb. Uncoated", "14pt Cardstock"],
    sizes: ['8.5" × 11"', '5.5" × 8.5"', '4" × 6"', '11" × 17"', "Custom"],
    finishes: ["None", "AQ Coating", "UV Coating", "Soft Touch"],
    folding: ["None", "Half-Fold", "Tri-Fold", "Accordion", "Z-Fold"],
    printedSides: ["Front Only", "Front & Back"],
    bundling: ["None", "25 per pack", "50 per pack", "100 per pack"],
    turnaround: ["3 Business Days", "2 Business Days", "Next Business Day"],
    highlights: [
      '8.5" × 11" and 6 other sizes plus custom sizes',
      "Gloss, matte, or uncoated paper options",
      "Optional folding: half-fold, tri-fold, accordion, and more",
      "Single- or double-sided printing",
    ],
    featured: true,
  },
  {
    id: "p3",
    name: "Custom Stickers",
    slug: "custom-stickers",
    category: "stickers",
    description:
      "Custom-shaped stickers for brands, packaging, and promotions—waterproof options, die-cut singles, rolls, and sheets.",
    price: 0.05,
    rating: 4.3,
    reviews: 2651,
    deliveryDays: 3,
    badge: "Top Rated",
    image: "stickers",
    images: ["stickers", "stickers-2", "labels"],
    imageUrl:
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1626785774573-4b7993143486?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=1200&q=80",
    ],
    productTypes: [
      { label: "Die-Cut Singles", value: "die-cut" },
      { label: "Roll", value: "roll" },
      { label: "Sheet", value: "sheet" },
      { label: "Kiss-Cut Singles", value: "kiss-cut" },
    ],
    materials: ["White Paper", "White Vinyl", "Clear Vinyl", "Kraft", "Holographic"],
    sizes: ['2" × 2"', '3" × 3"', '4" × 4"', '2" × 3"', "Custom"],
    finishes: ["Gloss Coating", "Matte Coating", "None"],
    bundling: ["None", "Sheet of 12", "Sheet of 24", "Roll of 250"],
    turnaround: ["3 Business Days", "2 Business Days", "Next Business Day"],
    highlights: [
      "Die-cut, kiss-cut, roll, and sheet formats",
      "Square, round, oval, and custom shapes",
      "Waterproof vinyl options available",
      "Indoor & outdoor durable materials",
    ],
    featured: true,
  },
  {
    id: "p4",
    name: "Vinyl Banners",
    slug: "vinyl-banners",
    category: "banners",
    description:
      "Weather-resistant vinyl banners with grommets—built for storefronts, events, and outdoor campaigns.",
    price: 39.99,
    rating: 4.7,
    reviews: 654,
    deliveryDays: 2,
    badge: "Fast Turnaround",
    image: "banners",
    images: ["banners", "banners-2"],
    imageUrl:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["13oz Vinyl", "18oz Scrim", "Mesh", "Fabric"],
    sizes: ["2' × 4'", "3' × 6'", "4' × 8'", "Custom"],
    finishes: ["Hemmed + Grommets", "Pole Pockets", "Stand Hardware"],
    printedSides: ["Front Only", "Front & Back"],
    turnaround: ["2 Business Days", "Next Business Day", "Same Day (local)"],
    highlights: [
      "Indoor & outdoor durable vinyl",
      "Hemmed edges with metal grommets",
      "Custom sizes available",
      "Fast 2-day production options",
    ],
    featured: true,
  },
  {
    id: "p5",
    name: "Tri-Fold Brochures",
    slug: "tri-fold-brochures",
    category: "brochures",
    description:
      "Professionally folded brochures on premium gloss or matte stock—menus, leave-behinds, and sales kits.",
    price: 49.99,
    rating: 4.8,
    reviews: 892,
    deliveryDays: 4,
    badge: "Popular",
    image: "brochures",
    images: ["brochures", "brochures-2"],
    imageUrl:
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["100lb Gloss", "100lb Matte", "80lb Uncoated"],
    sizes: ['8.5" × 11"', '11" × 17"', '5.5" × 8.5"'],
    finishes: ["Folded", "Scored", "AQ Coating"],
    folding: ["Tri-Fold", "Bi-Fold", "Z-Fold", "Accordion"],
    printedSides: ["Front & Back"],
    bundling: ["None", "25 per pack", "50 per pack"],
    turnaround: ["4 Business Days", "3 Business Days", "2 Business Days"],
    highlights: [
      "Restaurant menus & sales brochures",
      "Multiple fold styles",
      "Gloss or matte premium stocks",
      "Scored for clean folds",
    ],
    featured: true,
  },
  {
    id: "p6",
    name: "Event Posters",
    slug: "event-posters",
    category: "posters",
    description: "Vibrant large-format posters on photo-grade stock for events, retail, and campaigns.",
    price: 19.99,
    rating: 4.6,
    reviews: 512,
    deliveryDays: 2,
    image: "posters",
    images: ["posters"],
    imageUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["100lb Gloss", "12pt Cardstock", "Canvas"],
    sizes: ['11" × 17"', '18" × 24"', '24" × 36"'],
    finishes: ["None", "Laminate", "Mounting"],
    turnaround: ["2 Business Days", "Next Business Day"],
    highlights: [
      "Photo-quality color",
      "Multiple large formats",
      "Optional laminate & mounting",
      "Retail & event ready",
    ],
    featured: true,
  },
  {
    id: "p7",
    name: "Roll Labels",
    slug: "roll-labels",
    category: "labels",
    description: "Waterproof product labels wound for easy application—bottles, jars, and packaging.",
    price: 22.99,
    rating: 4.7,
    reviews: 778,
    deliveryDays: 4,
    image: "labels",
    images: ["labels"],
    imageUrl:
      "https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1626785774573-4b7993143486?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["White Vinyl", "Clear", "Metallic", "Kraft"],
    sizes: ['2" × 2"', '3" × 2"', '4" × 3"', "Custom"],
    finishes: ["Gloss", "Matte"],
    turnaround: ["4 Business Days", "3 Business Days", "2 Business Days"],
    highlights: [
      "Bottle & jar ready",
      "Waterproof vinyl options",
      "Wound on rolls for speed",
      "Custom shapes available",
    ],
    featured: true,
  },
  {
    id: "p8",
    name: "Rigid Product Boxes",
    slug: "rigid-product-boxes",
    category: "boxes",
    description: "Luxury rigid boxes with custom inserts for premium unboxing experiences.",
    price: 129.99,
    rating: 4.8,
    reviews: 341,
    deliveryDays: 7,
    badge: "Premium",
    image: "boxes",
    images: ["boxes", "boxes-2"],
    imageUrl:
      "https://images.unsplash.com/photo-1607083206968-13611e3d76db?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1607083206968-13611e3d76db?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["Rigid Chipboard", "Kraft", "Corrugated"],
    sizes: ["Small", "Medium", "Large", "Custom"],
    finishes: ["Soft Touch", "Foil Stamp", "Emboss", "Matte"],
    turnaround: ["7 Business Days", "5 Business Days", "10 Business Days"],
    highlights: [
      "Luxury rigid construction",
      "Custom inserts available",
      "Foil & soft-touch finishes",
      "Ideal for e-commerce unboxing",
    ],
    featured: true,
  },
  {
    id: "p9",
    name: "Die-Cut Stickers",
    slug: "die-cut-stickers",
    category: "stickers",
    description: "Waterproof vinyl stickers cut precisely to your artwork—great for coasters and branding.",
    price: 14.99,
    rating: 4.9,
    reviews: 2103,
    deliveryDays: 3,
    image: "stickers",
    images: ["stickers", "stickers-2"],
    imageUrl:
      "https://images.unsplash.com/photo-1626785774573-4b7993143486?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1626785774573-4b7993143486?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["Vinyl", "Clear Vinyl", "Holographic"],
    sizes: ['2"', '3"', '4"', "Custom"],
    finishes: ["Gloss", "Matte", "Kiss Cut"],
    turnaround: ["3 Business Days", "2 Business Days"],
    highlights: [
      "Cut to any custom shape",
      "Waterproof vinyl",
      "Indoor & outdoor use",
      "Bulk pricing available",
    ],
    featured: true,
  },
  {
    id: "p10",
    name: "Branded Tote Bags",
    slug: "branded-tote-bags",
    category: "promotional-products",
    description: "Eco-friendly canvas totes with full-color imprint for events and retail.",
    price: 8.99,
    rating: 4.5,
    reviews: 423,
    deliveryDays: 5,
    image: "promo",
    images: ["promo"],
    imageUrl:
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80",
    ],
    materials: ["Canvas", "Non-woven", "Cotton"],
    sizes: ["Standard", "Large"],
    finishes: ["1-Color", "Full Color"],
    turnaround: ["5 Business Days", "3 Business Days"],
    highlights: [
      "Eco-friendly materials",
      "Full-color imprint",
      "Event & retail ready",
      "Bulk discounts",
    ],
    featured: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Chen",
    role: "Brand Director",
    company: "Lumen Studio",
    avatar: "SC",
    rating: 5,
    quote:
      "Printoe elevated our collateral overnight. Color accuracy is unmatched, and turnaround never slips.",
    logo: "Lumen",
  },
  {
    id: "t2",
    name: "Marcus Webb",
    role: "Founder",
    company: "Northline Co.",
    avatar: "MW",
    rating: 5,
    quote:
      "We moved our entire print ops here. The configurator and artwork review saved us weeks of back-and-forth.",
    logo: "Northline",
  },
  {
    id: "t3",
    name: "Priya Nair",
    role: "Marketing Lead",
    company: "Cascade Health",
    avatar: "PN",
    rating: 5,
    quote:
      "Enterprise reliability with boutique quality. Our regional campaigns look consistently premium.",
    logo: "Cascade",
  },
  {
    id: "t4",
    name: "James Okonkwo",
    role: "Creative Ops",
    company: "Fieldwork Agency",
    avatar: "JO",
    rating: 5,
    quote:
      "From packaging prototypes to 10k runs, Printoe scales with us without sacrificing craft.",
    logo: "Fieldwork",
  },
  {
    id: "t5",
    name: "Elena Ruiz",
    role: "E-commerce Lead",
    company: "Orbit Goods",
    avatar: "ER",
    rating: 5,
    quote:
      "Our product boxes and labels finally match our brand online. Customers notice the unboxing—and so do we.",
    logo: "Orbit",
  },
  {
    id: "t6",
    name: "David Park",
    role: "COO",
    company: "Summit Events",
    avatar: "DP",
    rating: 5,
    quote:
      "Banners, badges, and programs for 40+ events a year—always on time, always print-perfect.",
    logo: "Summit",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    title: "How premium paper stocks shape brand perception",
    slug: "premium-paper-stocks-brand-perception",
    excerpt:
      "A practical guide to choosing substrates that signal quality before a single word is read.",
    category: "Print Craft",
    author: "Elena Vargas",
    date: "2026-06-12",
    readTime: "6 min",
    image: "blog-1",
    featured: true,
    trending: true,
  },
  {
    id: "b2",
    title: "Artwork prep checklist for flawless production",
    slug: "artwork-prep-checklist",
    excerpt:
      "Bleed, color profiles, fonts, and the small details that prevent costly reprints.",
    category: "Guides",
    author: "Tom Hale",
    date: "2026-06-02",
    readTime: "8 min",
    image: "blog-2",
    trending: true,
  },
  {
    id: "b3",
    title: "Sustainable packaging that still feels luxurious",
    slug: "sustainable-packaging-luxury",
    excerpt:
      "Eco materials and finishes that meet ESG goals without compromising unboxing moments.",
    category: "Sustainability",
    author: "Maya Brooks",
    date: "2026-05-21",
    readTime: "5 min",
    image: "blog-3",
    featured: true,
  },
  {
    id: "b4",
    title: "Scaling print campaigns across 50+ locations",
    slug: "scaling-print-campaigns",
    excerpt:
      "Operational patterns brands use to keep visual consistency at regional scale.",
    category: "Enterprise",
    author: "Chris Park",
    date: "2026-05-08",
    readTime: "7 min",
    image: "blog-4",
  },
];

export const services: Service[] = [
  {
    id: "s1",
    name: "Graphic Design",
    description: "Campaign-ready layouts engineered for print production.",
    icon: "Palette",
  },
  {
    id: "s2",
    name: "Logo Design",
    description: "Marks built to reproduce cleanly across every substrate.",
    icon: "Sparkles",
  },
  {
    id: "s3",
    name: "Brand Identity",
    description: "Systems that keep your visual language consistent at scale.",
    icon: "Layers",
  },
  {
    id: "s4",
    name: "Packaging Design",
    description: "Structural and surface design for memorable unboxing.",
    icon: "PackageOpen",
  },
  {
    id: "s5",
    name: "Marketing Materials",
    description: "Full suites from leave-behinds to trade-show kits.",
    icon: "LayoutTemplate",
  },
  {
    id: "s6",
    name: "Custom Printing",
    description: "Specialty runs with unique finishes and formats.",
    icon: "Printer",
  },
  {
    id: "s7",
    name: "Large Format Printing",
    description: "Banners, wraps, and displays with color-managed output.",
    icon: "Maximize2",
  },
  {
    id: "s8",
    name: "Business Stationery",
    description: "Letterheads, envelopes, and executive presentation sets.",
    icon: "Briefcase",
  },
];

export const whyChooseUs = [
  {
    title: "Free Artwork Review",
    description: "Expert preflight on every file before we print.",
    icon: "FileSearch",
  },
  {
    title: "Fast Delivery",
    description: "Express options as quick as next-day shipping.",
    icon: "Zap",
  },
  {
    title: "Premium Printing Quality",
    description: "Color-managed presses and calibrated proofs.",
    icon: "Award",
  },
  {
    title: "Bulk Discounts",
    description: "Transparent volume pricing that scales with you.",
    icon: "Percent",
  },
  {
    title: "Secure Payments",
    description: "PCI-compliant checkout with enterprise invoicing.",
    icon: "ShieldCheck",
  },
  {
    title: "Eco-Friendly Printing",
    description: "FSC papers and low-VOC inks available.",
    icon: "Leaf",
  },
  {
    title: "Dedicated Support",
    description: "Specialists available for multi-location teams.",
    icon: "Headphones",
  },
  {
    title: "Satisfaction Guarantee",
    description: "We reprint if quality misses our standard.",
    icon: "BadgeCheck",
  },
];

export const processSteps = [
  { title: "Choose Product", description: "Browse curated print categories", icon: "Search" },
  { title: "Customize", description: "Configure size, stock & finish", icon: "SlidersHorizontal" },
  { title: "Upload Artwork", description: "Drop files or design online", icon: "Upload" },
  { title: "Checkout", description: "Secure payment & scheduling", icon: "CreditCard" },
  { title: "Printing", description: "Color-managed production", icon: "Printer" },
  { title: "Delivery", description: "Tracked shipping worldwide", icon: "Truck" },
];

export const stats = [
  { label: "Orders Completed", value: 1250000, suffix: "+" },
  { label: "Customers Served", value: 84000, suffix: "+" },
  { label: "Products Available", value: 520, suffix: "+" },
  { label: "Years of Experience", value: 18, suffix: "" },
  { label: "Customer Satisfaction", value: 98.6, suffix: "%" },
];

export const portfolioItems = [
  { id: "g1", title: "Retail packaging suite", category: "Packaging", tall: true },
  { id: "g2", title: "Launch event posters", category: "Posters", tall: false },
  { id: "g3", title: "Executive stationery", category: "Stationery", tall: false },
  { id: "g4", title: "Before / After label redesign", category: "Labels", tall: true, beforeAfter: true },
  { id: "g5", title: "Trade show booth kit", category: "Large Format", tall: false },
  { id: "g6", title: "Seasonal brochure campaign", category: "Brochures", tall: true },
];

export const orders: Order[] = [
  {
    id: "ORD-10482",
    product: "Silk Business Cards",
    status: "printing",
    date: "2026-07-18",
    total: 89.97,
    quantity: 500,
  },
  {
    id: "ORD-10471",
    product: "Vinyl Banners",
    status: "shipped",
    date: "2026-07-15",
    total: 159.96,
    quantity: 4,
  },
  {
    id: "ORD-10455",
    product: "Tri-Fold Brochures",
    status: "delivered",
    date: "2026-07-08",
    total: 249.95,
    quantity: 1000,
  },
  {
    id: "ORD-10440",
    product: "Die-Cut Stickers",
    status: "processing",
    date: "2026-07-19",
    total: 44.97,
    quantity: 250,
  },
];

export const cartItems: CartItem[] = [
  {
    id: "c1",
    productId: "p1",
    name: "Silk Business Cards",
    image: "business-cards",
    quantity: 500,
    unitPrice: 0.06,
    size: '3.5" × 2"',
    material: "16pt Soft Touch",
    finishing: "Soft Touch",
  },
  {
    id: "c2",
    productId: "p9",
    name: "Die-Cut Stickers",
    image: "stickers",
    quantity: 250,
    unitPrice: 0.08,
    size: '3"',
    material: "Vinyl",
    finishing: "Gloss",
  },
];

export const navCategories = categories.slice(0, 8);
