import type {
  BlogPost,
  CartItem,
  Order,
  Product,
  ProductCategory,
  Service,
  Testimonial,
} from "@/types";

export const SITE = {
  name: "Printoe",
  tagline: "Enterprise print, perfected.",
  description:
    "Premium online printing for brands that demand precision, speed, and craftsmanship.",
  url: "https://printoe.com",
  email: "hello@printoe.com",
  phone: "+1 (888) 555-0199",
  address: "450 Market Street, Suite 1200, San Francisco, CA 94105",
};

export const categories: ProductCategory[] = [
  {
    id: "1",
    name: "Business Cards",
    slug: "business-cards",
    description: "Premium stock with crisp finishes",
    count: 48,
    startingPrice: 19.99,
    icon: "CreditCard",
    color: "#E6007A",
  },
  {
    id: "2",
    name: "Flyers",
    slug: "flyers",
    description: "High-impact promotional prints",
    count: 36,
    startingPrice: 24.99,
    icon: "FileText",
    color: "#00AEEF",
  },
  {
    id: "3",
    name: "Brochures",
    slug: "brochures",
    description: "Folded storytelling that converts",
    count: 28,
    startingPrice: 39.99,
    icon: "BookOpen",
    color: "#1A1A1A",
  },
  {
    id: "4",
    name: "Posters",
    slug: "posters",
    description: "Large format visual impact",
    count: 42,
    startingPrice: 14.99,
    icon: "Image",
    color: "#00A651",
  },
  {
    id: "5",
    name: "Stickers",
    slug: "stickers",
    description: "Die-cut or sheet, waterproof options",
    count: 64,
    startingPrice: 9.99,
    icon: "Sticker",
    color: "#FFD400",
  },
  {
    id: "6",
    name: "Labels",
    slug: "labels",
    description: "Product & shipping ready",
    count: 52,
    startingPrice: 12.99,
    icon: "Tag",
    color: "#E30613",
  },
  {
    id: "7",
    name: "Packaging",
    slug: "packaging",
    description: "Custom unboxing experiences",
    count: 31,
    startingPrice: 89.99,
    icon: "Package",
    color: "#E6007A",
  },
  {
    id: "8",
    name: "Boxes",
    slug: "boxes",
    description: "Rigid, mailer & folding cartons",
    count: 24,
    startingPrice: 79.99,
    icon: "Box",
    color: "#00AEEF",
  },
  {
    id: "9",
    name: "Banners",
    slug: "banners",
    description: "Indoor & outdoor durability",
    count: 38,
    startingPrice: 29.99,
    icon: "Flag",
    color: "#1A1A1A",
  },
  {
    id: "10",
    name: "Marketing Materials",
    slug: "marketing-materials",
    description: "Campaign kits that scale",
    count: 56,
    startingPrice: 34.99,
    icon: "Megaphone",
    color: "#00A651",
  },
  {
    id: "11",
    name: "Apparel",
    slug: "apparel",
    description: "Branded wear for teams & events",
    count: 44,
    startingPrice: 18.99,
    icon: "Shirt",
    color: "#FFD400",
  },
  {
    id: "12",
    name: "Promotional Products",
    slug: "promotional-products",
    description: "Memorable branded giveaways",
    count: 72,
    startingPrice: 4.99,
    icon: "Gift",
    color: "#E30613",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Silk Business Cards",
    slug: "silk-business-cards",
    category: "business-cards",
    description:
      "Soft-touch laminated cards with razor-sharp color and a luxurious matte feel.",
    price: 29.99,
    compareAt: 39.99,
    rating: 4.9,
    reviews: 1284,
    deliveryDays: 3,
    badge: "Best Seller",
    image: "business-cards",
    images: ["business-cards", "business-cards-2", "business-cards-3"],
    materials: ["16pt Soft Touch", "14pt Matte", "18pt Spot UV"],
    sizes: ['3.5" × 2"', '3.5" × 2" Rounded', "Square 2.5\""],
    finishes: ["Matte", "Soft Touch", "Spot UV", "Foil"],
    featured: true,
  },
  {
    id: "p2",
    name: "Tri-Fold Brochures",
    slug: "tri-fold-brochures",
    category: "brochures",
    description:
      "Professionally folded brochures on premium gloss or matte stock.",
    price: 49.99,
    rating: 4.8,
    reviews: 892,
    deliveryDays: 4,
    badge: "Popular",
    image: "brochures",
    images: ["brochures", "brochures-2"],
    materials: ["100lb Gloss", "100lb Matte", "80lb Uncoated"],
    sizes: ['8.5" × 11"', '11" × 17"', '5.5" × 8.5"'],
    finishes: ["Folded", "Scored", "AQ Coating"],
    featured: true,
  },
  {
    id: "p3",
    name: "Vinyl Banners",
    slug: "vinyl-banners",
    category: "banners",
    description: "Weather-resistant vinyl with grommets for indoor or outdoor display.",
    price: 39.99,
    rating: 4.7,
    reviews: 654,
    deliveryDays: 2,
    badge: "Fast Turnaround",
    image: "banners",
    images: ["banners", "banners-2"],
    materials: ["13oz Vinyl", "18oz Scrim", "Mesh"],
    sizes: ['2\' × 4\'', '3\' × 6\'', '4\' × 8\'', "Custom"],
    finishes: ["Hemmed", "Grommets", "Pole Pockets"],
    featured: true,
  },
  {
    id: "p4",
    name: "Die-Cut Stickers",
    slug: "die-cut-stickers",
    category: "stickers",
    description: "Waterproof vinyl stickers cut precisely to your artwork.",
    price: 14.99,
    rating: 4.9,
    reviews: 2103,
    deliveryDays: 3,
    image: "stickers",
    images: ["stickers", "stickers-2"],
    materials: ["Vinyl", "Clear Vinyl", "Holographic"],
    sizes: ['2"', '3"', '4"', "Custom"],
    finishes: ["Gloss", "Matte", "Kiss Cut"],
    featured: true,
  },
  {
    id: "p5",
    name: "Rigid Product Boxes",
    slug: "rigid-product-boxes",
    category: "boxes",
    description: "Luxury rigid boxes with custom inserts for premium unboxing.",
    price: 129.99,
    rating: 4.8,
    reviews: 341,
    deliveryDays: 7,
    badge: "Premium",
    image: "boxes",
    images: ["boxes", "boxes-2"],
    materials: ["Rigid Chipboard", "Kraft", "Corrugated"],
    sizes: ["Small", "Medium", "Large", "Custom"],
    finishes: ["Soft Touch", "Foil Stamp", "Emboss"],
    featured: true,
  },
  {
    id: "p6",
    name: "Event Posters",
    slug: "event-posters",
    category: "posters",
    description: "Vibrant large-format posters on photo-grade stock.",
    price: 19.99,
    rating: 4.6,
    reviews: 512,
    deliveryDays: 2,
    image: "posters",
    images: ["posters"],
    materials: ["100lb Gloss", "12pt Cardstock", "Canvas"],
    sizes: ['11" × 17"', '18" × 24"', '24" × 36"'],
    finishes: ["Laminate", "Mounting"],
    featured: true,
  },
  {
    id: "p7",
    name: "Roll Labels",
    slug: "roll-labels",
    category: "labels",
    description: "Waterproof product labels wound for easy application.",
    price: 22.99,
    rating: 4.7,
    reviews: 778,
    deliveryDays: 4,
    image: "labels",
    images: ["labels"],
    materials: ["White Vinyl", "Clear", "Metallic"],
    sizes: ['2" × 2"', '3" × 2"', "Custom"],
    finishes: ["Gloss", "Matte"],
  },
  {
    id: "p8",
    name: "Branded Tote Bags",
    slug: "branded-tote-bags",
    category: "promotional-products",
    description: "Eco-friendly canvas totes with full-color imprint.",
    price: 8.99,
    rating: 4.5,
    reviews: 423,
    deliveryDays: 5,
    image: "promo",
    images: ["promo"],
    materials: ["Canvas", "Non-woven", "Cotton"],
    sizes: ["Standard", "Large"],
    finishes: ["1-Color", "Full Color"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Chen",
    role: "Brand Director",
    company: "Lumen Studio",
    avatar: "SC",
    rating: 5,
    quote:
      "Printoe elevated our collateral overnight. Color accuracy is unmatched, and turnaround never slips.",
    logo: "Lumen",
  },
  {
    id: "t2",
    name: "Marcus Webb",
    role: "Founder",
    company: "Northline Co.",
    avatar: "MW",
    rating: 5,
    quote:
      "We moved our entire print ops here. The configurator and artwork review saved us weeks of back-and-forth.",
    logo: "Northline",
  },
  {
    id: "t3",
    name: "Priya Nair",
    role: "Marketing Lead",
    company: "Cascade Health",
    avatar: "PN",
    rating: 5,
    quote:
      "Enterprise reliability with boutique quality. Our regional campaigns look consistently premium.",
    logo: "Cascade",
  },
  {
    id: "t4",
    name: "James Okonkwo",
    role: "Creative Ops",
    company: "Fieldwork Agency",
    avatar: "JO",
    rating: 5,
    quote:
      "From packaging prototypes to 10k runs, Printoe scales with us without sacrificing craft.",
    logo: "Fieldwork",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    title: "How premium paper stocks shape brand perception",
    slug: "premium-paper-stocks-brand-perception",
    excerpt:
      "A practical guide to choosing substrates that signal quality before a single word is read.",
    category: "Print Craft",
    author: "Elena Vargas",
    date: "2026-06-12",
    readTime: "6 min",
    image: "blog-1",
    featured: true,
    trending: true,
  },
  {
    id: "b2",
    title: "Artwork prep checklist for flawless production",
    slug: "artwork-prep-checklist",
    excerpt:
      "Bleed, color profiles, fonts, and the small details that prevent costly reprints.",
    category: "Guides",
    author: "Tom Hale",
    date: "2026-06-02",
    readTime: "8 min",
    image: "blog-2",
    trending: true,
  },
  {
    id: "b3",
    title: "Sustainable packaging that still feels luxurious",
    slug: "sustainable-packaging-luxury",
    excerpt:
      "Eco materials and finishes that meet ESG goals without compromising unboxing moments.",
    category: "Sustainability",
    author: "Maya Brooks",
    date: "2026-05-21",
    readTime: "5 min",
    image: "blog-3",
    featured: true,
  },
  {
    id: "b4",
    title: "Scaling print campaigns across 50+ locations",
    slug: "scaling-print-campaigns",
    excerpt:
      "Operational patterns brands use to keep visual consistency at regional scale.",
    category: "Enterprise",
    author: "Chris Park",
    date: "2026-05-08",
    readTime: "7 min",
    image: "blog-4",
  },
];

export const services: Service[] = [
  {
    id: "s1",
    name: "Graphic Design",
    description: "Campaign-ready layouts engineered for print production.",
    icon: "Palette",
  },
  {
    id: "s2",
    name: "Logo Design",
    description: "Marks built to reproduce cleanly across every substrate.",
    icon: "Sparkles",
  },
  {
    id: "s3",
    name: "Brand Identity",
    description: "Systems that keep your visual language consistent at scale.",
    icon: "Layers",
  },
  {
    id: "s4",
    name: "Packaging Design",
    description: "Structural and surface design for memorable unboxing.",
    icon: "PackageOpen",
  },
  {
    id: "s5",
    name: "Marketing Materials",
    description: "Full suites from leave-behinds to trade-show kits.",
    icon: "LayoutTemplate",
  },
  {
    id: "s6",
    name: "Custom Printing",
    description: "Specialty runs with unique finishes and formats.",
    icon: "Printer",
  },
  {
    id: "s7",
    name: "Large Format Printing",
    description: "Banners, wraps, and displays with color-managed output.",
    icon: "Maximize2",
  },
  {
    id: "s8",
    name: "Business Stationery",
    description: "Letterheads, envelopes, and executive presentation sets.",
    icon: "Briefcase",
  },
];

export const whyChooseUs = [
  {
    title: "Free Artwork Review",
    description: "Expert preflight on every file before we print.",
    icon: "FileSearch",
  },
  {
    title: "Fast Delivery",
    description: "Express options as quick as next-day shipping.",
    icon: "Zap",
  },
  {
    title: "Premium Printing Quality",
    description: "Color-managed presses and calibrated proofs.",
    icon: "Award",
  },
  {
    title: "Bulk Discounts",
    description: "Transparent volume pricing that scales with you.",
    icon: "Percent",
  },
  {
    title: "Secure Payments",
    description: "PCI-compliant checkout with enterprise invoicing.",
    icon: "ShieldCheck",
  },
  {
    title: "Eco-Friendly Printing",
    description: "FSC papers and low-VOC inks available.",
    icon: "Leaf",
  },
  {
    title: "Dedicated Support",
    description: "Specialists available for multi-location teams.",
    icon: "Headphones",
  },
  {
    title: "Satisfaction Guarantee",
    description: "We reprint if quality misses our standard.",
    icon: "BadgeCheck",
  },
];

export const processSteps = [
  { title: "Choose Product", description: "Browse curated print categories", icon: "Search" },
  { title: "Customize", description: "Configure size, stock & finish", icon: "SlidersHorizontal" },
  { title: "Upload Artwork", description: "Drop files or design online", icon: "Upload" },
  { title: "Checkout", description: "Secure payment & scheduling", icon: "CreditCard" },
  { title: "Printing", description: "Color-managed production", icon: "Printer" },
  { title: "Delivery", description: "Tracked shipping worldwide", icon: "Truck" },
];

export const stats = [
  { label: "Orders Completed", value: 1250000, suffix: "+" },
  { label: "Customers Served", value: 84000, suffix: "+" },
  { label: "Products Available", value: 520, suffix: "+" },
  { label: "Years of Experience", value: 18, suffix: "" },
  { label: "Customer Satisfaction", value: 98.6, suffix: "%" },
];

export const portfolioItems = [
  { id: "g1", title: "Retail packaging suite", category: "Packaging", tall: true },
  { id: "g2", title: "Launch event posters", category: "Posters", tall: false },
  { id: "g3", title: "Executive stationery", category: "Stationery", tall: false },
  { id: "g4", title: "Before / After label redesign", category: "Labels", tall: true, beforeAfter: true },
  { id: "g5", title: "Trade show booth kit", category: "Large Format", tall: false },
  { id: "g6", title: "Seasonal brochure campaign", category: "Brochures", tall: true },
];

export const orders: Order[] = [
  {
    id: "ORD-10482",
    product: "Silk Business Cards",
    status: "printing",
    date: "2026-07-18",
    total: 89.97,
    quantity: 500,
  },
  {
    id: "ORD-10471",
    product: "Vinyl Banners",
    status: "shipped",
    date: "2026-07-15",
    total: 159.96,
    quantity: 4,
  },
  {
    id: "ORD-10455",
    product: "Tri-Fold Brochures",
    status: "delivered",
    date: "2026-07-08",
    total: 249.95,
    quantity: 1000,
  },
  {
    id: "ORD-10440",
    product: "Die-Cut Stickers",
    status: "processing",
    date: "2026-07-19",
    total: 44.97,
    quantity: 250,
  },
];

export const cartItems: CartItem[] = [
  {
    id: "c1",
    productId: "p1",
    name: "Silk Business Cards",
    image: "business-cards",
    quantity: 500,
    unitPrice: 0.06,
    size: '3.5" × 2"',
    material: "16pt Soft Touch",
    finishing: "Soft Touch",
  },
  {
    id: "c2",
    productId: "p4",
    name: "Die-Cut Stickers",
    image: "stickers",
    quantity: 250,
    unitPrice: 0.08,
    size: '3"',
    material: "Vinyl",
    finishing: "Gloss",
  },
];

export const navCategories = categories.slice(0, 8);
